/** @file Binaries_To_Header_Converter.c
 * Embed a list of binary files data into a C-language header file.
 * @author Adrien RICCIARDI
 * @version 1.0 : ???
 * @version 1.1 : 26/04/2014, ported this program from a very old one version.
 * @version 1.2 : 27/04/2014, used more complete structures to represent the files.
 */
#include <stdio.h>
#include <stdlib.h>

//-------------------------------------------------------------------------------------------------------------------------------
// Private constants
//-------------------------------------------------------------------------------------------------------------------------------
/** How long the array lines must be. */
#define CHARACTERS_PER_LINE_COUNT 20

/** Maximum number of files this program can process. */
#define MAXIMUM_PROCESSED_FILES_COUNT 256

//-------------------------------------------------------------------------------------------------------------------------------
// Private types
//-------------------------------------------------------------------------------------------------------------------------------
/** Contain the C initialization syntax of an embedded file array entry. */
typedef struct
{
	char String_File_Name[64]; //! The name to give to the file when created on the target file system.
	int File_Size_Bytes; //! The file size in bytes.
	char String_Variable_Name[64]; //! Hold the name of the array variable containing the data.
} TEmbeddedFileEntry;

//-------------------------------------------------------------------------------------------------------------------------------
// Private variables
//-------------------------------------------------------------------------------------------------------------------------------
TEmbeddedFileEntry Embedded_Files_Entries[MAXIMUM_PROCESSED_FILES_COUNT];

//-------------------------------------------------------------------------------------------------------------------------------
// Private functions
//-------------------------------------------------------------------------------------------------------------------------------
void FatalError(char *String_Message)
{
	printf("Error : %s.\n", String_Message);
	exit(EXIT_FAILURE);
}

/** Find the file of a file.
 * @param String_File_Name The name of the file to find size.
 * @return The file size in bytes or -1 if the file could not be found.
 */
static int FileSize(char *String_File_Name)
{
	FILE *File;
	long Size_Bytes;
	
	// Open the file and go to its end
	File = fopen(String_File_Name, "a");
	if (File == NULL) return -1;
	
	// Get the file size
	Size_Bytes = ftell(File);
	fclose(File);
	return (int) Size_Bytes;
}

/** Write the comments and type definition.
 * @param File_Destination The file to write to.
 */
static void WriteHeaderFileBeginning(FILE *File_Destination)
{
	// Header
	fprintf(File_Destination, "/** This file has been automatically generated by Binaries_To_Header_Converter. */\n");
	fprintf(File_Destination, "#ifndef H_EMBEDDED_FILES_DATA_H\n#define H_EMBEDDED_FILES_DATA_H\n\n");
	
	// Includes
	fprintf(File_Destination, "#include <Configuration.h> // To have CONFIGURATION_FILE_NAME_LENGTH constant\n\n");
	
	// Type definition
	fprintf(File_Destination, "//-------------------------------------------------------------------------------------------------------------------------------\n");
	fprintf(File_Destination, "// Types\n");
	fprintf(File_Destination, "//-------------------------------------------------------------------------------------------------------------------------------\n");
	fprintf(File_Destination, "/** Represent an embedded file. */\n");
	fprintf(File_Destination, "typedef struct\n{\n");
	fprintf(File_Destination, "\tchar String_Name[CONFIGURATION_FILE_NAME_LENGTH + 1];\n");
	fprintf(File_Destination, "\tunsigned int Size_Bytes;\n");
	fprintf(File_Destination, "\tunsigned char *Pointer_Data;\n");
	fprintf(File_Destination, "} TEmbeddedFile;\n\n");
	
	fprintf(File_Destination, "//-------------------------------------------------------------------------------------------------------------------------------\n");
	fprintf(File_Destination, "// Variables\n");
	fprintf(File_Destination, "//-------------------------------------------------------------------------------------------------------------------------------\n");
}

/** Convert the content of a binary file into a C array of bytes.
 * @param File_Source The binary file to convert.
 * @param File_Destination The C file to write the array to.
 * @param Bytes_Count How many bytes to convert.
 * @param String_Variable_Name The variable name to give to the array.
 */
static void ConvertBinaryFile(FILE *File_Source, FILE *File_Destination, int Bytes_Count, char *String_Variable_Name)
{
	unsigned char Byte;
	int i, Characters_Count = 0;
	
	// Write the array variable name
	fprintf(File_Destination, "unsigned char %s[] =\n{\n", String_Variable_Name);
	
	for (i = 0; i < Bytes_Count; i++)
	{
		// Add a tabulation if this is the first character of the line
		if (Characters_Count == 0) fprintf(File_Destination, "\t");
		
		fscanf(File_Source, "%c", &Byte);
		fprintf(File_Destination, "0x%02X", Byte);
		
		// Add a comma if the previously written byte is not the last one of the file
		if (i < (Bytes_Count - 1)) fprintf(File_Destination, ", ");
		else
		{
			fprintf(File_Destination, "\n");
			break;
		}
		
		Characters_Count++;
		if (Characters_Count >= CHARACTERS_PER_LINE_COUNT)
		{
			// Go to next line
			fprintf(File_Destination, "\n");
			Characters_Count = 0;
		}
	}
	
	// Close array scope
	fprintf(File_Destination, "};\n\n");
}

/** Write the entries array variable to a file.
 * @param File_Destination The file to write to.
 * @param Pointer_Entries The embedded file entries.
 * @param Entries_Count How many entries to write.
 */
static void WriteEntriesArray(FILE *File_Destination, TEmbeddedFileEntry *Pointer_Entries, int Entries_Count)
{
	int i;
	
	// Write array variable declaration
	fprintf(File_Destination, "TEmbeddedFile Embedded_Files[] =\n{\n");
	
	// Write array content
	for (i = 0; i < Entries_Count; i++) fprintf(File_Destination, "\t{ \"%s\", %d, %s },\n", Pointer_Entries[i].String_File_Name, Pointer_Entries[i].File_Size_Bytes, Pointer_Entries[i].String_Variable_Name);
	
	// Close array scope
	fprintf(File_Destination, "};\n\n");
}

//-------------------------------------------------------------------------------------------------------------------------------
// Entry point
//-------------------------------------------------------------------------------------------------------------------------------
int main(int argc, char *argv[])
{
	char String_Binary_File_Name[512];
	FILE *File_List, *File_Output, *File_Binary_Source;
	int Binary_File_Size, Processed_Files_Count = 0;
	
	// Check parameters
	if (argc != 3)
	{
		printf("Error : bad parameters.\nUsage : %s binariesListFile outputHeaderFile\n", argv[0]);
		return EXIT_FAILURE;
	}
	
	// Open files
	File_List = fopen(argv[1], "r");
	if (File_List == NULL) FatalError("can't open list file");
	File_Output = fopen(argv[2], "w");
	if (File_Output == NULL) FatalError("can't create output file");
	
	// Write the beginning of the file (up to the variables initialization)
	WriteHeaderFileBeginning(File_Output);
	
	// Convert files to C arrays
	while (1)
	{
		// Read the next binary file name
		fscanf(File_List, "%s", String_Binary_File_Name);
		if (feof(File_List)) break;
		
		// Open this file
		File_Binary_Source = fopen(String_Binary_File_Name, "rb");
		if (File_Binary_Source == NULL)
		{
			printf("Error : the file '%s' could not be found.\n", String_Binary_File_Name);
			return EXIT_FAILURE;
		}
		
		// Read the target file system file name to give to this binary file
		fscanf(File_List, "%s", Embedded_Files_Entries[Processed_Files_Count].String_File_Name);
		if (Embedded_Files_Entries[Processed_Files_Count].String_File_Name[0] == 0)
		{
			printf("Error : the file '%s' has no target file name.\n", String_Binary_File_Name);
			return EXIT_FAILURE;
		}
		
		// Find the file size
		Binary_File_Size = FileSize(String_Binary_File_Name);
		Embedded_Files_Entries[Processed_Files_Count].File_Size_Bytes = Binary_File_Size;
		
		// Generate the variable name
		sprintf(Embedded_Files_Entries[Processed_Files_Count].String_Variable_Name, "File_%d_Data", Processed_Files_Count);
		
		// Convert the file data
		printf("Converting file '%s'...\n", String_Binary_File_Name);
		ConvertBinaryFile(File_Binary_Source, File_Output, Binary_File_Size, Embedded_Files_Entries[Processed_Files_Count].String_Variable_Name);
		
		fclose(File_Binary_Source);
		printf("Conversion successfully completed (%d processed bytes).\n", Binary_File_Size);
		Processed_Files_Count++;
	}
	
	// Write the entries array referencing all the data arrays
	WriteEntriesArray(File_Output, (TEmbeddedFileEntry *) &Embedded_Files_Entries, Processed_Files_Count);
	
	fprintf(File_Output, "#endif");
	
	fclose(File_List);
	fclose(File_Output);
	printf("All files have been successfully converted.\n");
	
	return EXIT_SUCCESS;
}
	