GLOBAL_PROCESSOR_TYPE = nehalem

SYSTEM_HARD_DISK_DRIVER = sata
SYSTEM_HARD_DISK_LOGICAL_BLOCK_ADDRESSING_MODE = 48

SYSTEM_RAM_SIZE = 1024

# SYSTEM_INSTALLER_FILES_LIST
include $(LEMON_PATH_CONFIGURATIONS)/Template_Installer_Files_List_Network_Disabled.mk