GLOBAL_PROCESSOR_TYPE = pentium

SYSTEM_HARD_DISK_LOGICAL_BLOCK_ADDRESSING_MODE = 28

SYSTEM_ETHERNET_CONTROLLER_DRIVER = 82540em

SYSTEM_RAM_SIZE = 16

# SYSTEM_INSTALLER_FILES_LIST
include $(LEMON_PATH_CONFIGURATIONS)/Template_Installer_Files_List_Network_Enabled.mk
